---
abstract: 'Attempt to determine the current command Dist::Zilla is running under.'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Moose: '2.1205'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.008, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Util-CurrentCmd
provides:
  Dist::Zilla::Util::CurrentCmd:
    file: lib/Dist/Zilla/Util/CurrentCmd.pm
    version: '0.002004'
recommends:
  Moose: '2.000'
requires:
  Moose: '2.1205'
  Sub::Exporter: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/Dist-Zilla-Util-CurrentCmd/issues
  homepage: https://github.com/kentnl/Dist-Zilla-Util-CurrentCmd
  repository: https://github.com/kentnl/Dist-Zilla-Util-CurrentCmd.git
version: '0.002004'
